create database WalmartInsightHub;
use WalmartInsightHub;

-- Q1. What is the Sales Summary by Branch?
SELECT 
    Branch, 
    SUM(Total) AS Total_Sales
FROM Walmart_Dataset
GROUP BY Branch
ORDER BY Total_Sales DESC;

-- Q2.What is the average sales amount by gender?  
SELECT 
    Gender, 
    AVG(Total) AS Average_Sales
FROM Walmart_Dataset
GROUP BY Gender
ORDER BY Average_Sales DESC;

-- Q3. What is the total quantity sold for each product line?  
SELECT 
    Product_Line, 
    SUM(Quantity) AS Total_Quantity
FROM Walmart_Dataset
GROUP BY Product_Line
ORDER BY Total_Quantity DESC;

-- Q4. How much gross income is generated by each customer type?  
SELECT 
    Customer_Type, 
    SUM(Gross_Income) AS Total_Gross_Income
FROM Walmart_Dataset
GROUP BY Customer_Type
ORDER BY Total_Gross_Income DESC;

-- Q5. What is the average customer rating for each payment method? 
SELECT 
    Payment, 
    AVG(Rating) AS Average_Rating
FROM Walmart_Dataset
GROUP BY Payment
ORDER BY Average_Rating DESC;

-- Q6. Which are the top 3 cities by sales revenue?  
SELECT 
    City, 
    SUM(Total) AS Total_Sales
FROM Walmart_Dataset
GROUP BY City
ORDER BY Total_Sales DESC
LIMIT 3;

-- Q7. How does sales performance vary by branch and gender?  
SELECT 
    Branch, 
    Gender, 
    SUM(Total) AS Total_Sales
FROM Walmart_Dataset
GROUP BY Branch, Gender
ORDER BY Branch, Gender;

-- Q8. What is the percentage contribution of each payment method to total sales?  
SELECT 
    Payment, 
    SUM(Total) AS Total_Sales,
    ROUND((SUM(Total) * 100.0 / (SELECT SUM(Total) FROM Walmart_Dataset)), 2) AS Percentage_Contribution
FROM Walmart_Dataset
GROUP BY Payment
ORDER BY Percentage_Contribution DESC;

-- Q9. How much gross income is generated by each product line? 
SELECT 
    Product_Line, 
    SUM(Gross_Income) AS Total_Gross_Income
FROM Walmart_Dataset
GROUP BY Product_Line
ORDER BY Total_Gross_Income DESC;

-- Q10. What is the average customer rating in each city?
SELECT 
    City, 
    AVG(Rating) AS Average_Rating
FROM Walmart_Dataset
GROUP BY City
ORDER BY Average_Rating DESC;

-- Q11. What is the sales contribution of each customer type? 
SELECT 
    Customer_Type, 
    SUM(Total) AS Total_Sales
FROM Walmart_Dataset
GROUP BY Customer_Type
ORDER BY Total_Sales DESC;

-- Q12. How is the sales distributed among the different payment methods?
SELECT 
    Payment, 
    COUNT(*) AS Number_of_Transactions,
    SUM(Total) AS Total_Sales
FROM Walmart_Dataset
GROUP BY Payment
ORDER BY Total_Sales DESC;

-- Q13. What are the top 5 highest-rated transactions? 
SELECT 
    InvoiceID, 
    Rating, 
    Total, 
    Product_Line
FROM Walmart_Dataset
ORDER BY Rating DESC             
LIMIT 5;

-- Q14. How many total transactions occurred at each branch?  
SELECT 
    Branch, 
    COUNT(*) AS Transaction_Count
FROM Walmart_Dataset
GROUP BY Branch
ORDER BY Transaction_Count DESC;

-- Q15. Which customer type has the highest spending? 
SELECT 
    Customer_Type, 
    MAX(Total) AS Highest_Sale
FROM Walmart_Dataset
GROUP BY Customer_Type
ORDER BY Highest_Sale DESC;

-- Q16. Which transactions have the maximum quantity sold? 
SELECT 
    InvoiceID, 
    Quantity, 
    Product_Line
FROM Walmart_Dataset
WHERE Quantity = (SELECT MAX(Quantity) FROM Walmart_Dataset);

-- Q17. How much total tax has been collected for each payment method?  
SELECT 
    Payment, 
    SUM(`Tax_5%`) AS Total_Tax
FROM Walmart_Dataset
GROUP BY Payment
ORDER BY Total_Tax DESC;

-- Q18. What is the average quantity sold for each product line?
SELECT 
    Product_Line, 
    AVG(Quantity) AS Average_Quantity
FROM Walmart_Dataset
GROUP BY Product_Line
ORDER BY Average_Quantity DESC;


-- 19. What is the most popular product line by total revenue?
SELECT Product_Line, SUM(Total) AS Total_Revenue
FROM Walmart_Dataset
GROUP BY Product_Line
HAVING SUM(Total) = (
    SELECT MAX(Total)
    FROM (
        SELECT Product_Line, SUM(Total) AS Total
        FROM Walmart_Dataset
        GROUP BY Product_Line
    ) AS Subquery
);

-- Q20. Which cities have above-average gross income?
SELECT City, AVG(gross_income) AS Avg_Gross_Income
FROM Walmart_Dataset
GROUP BY City
HAVING AVG(gross_income) > (
    SELECT AVG(gross_income) FROM Walmart_Dataset
);

-- Q21. How can ratings be categorized effectively?
SELECT InvoiceID, Rating,
    CASE 
        WHEN Rating < 5 THEN 'Low'
        WHEN Rating BETWEEN 5 AND 7 THEN 'Medium'
        ELSE 'High'
    END AS Rating_Category
FROM Walmart_Dataset;

-- Q22. How are discounts calculated for products or services?
SELECT InvoiceID, Quantity, Unit_price,
    CASE 
        WHEN Quantity >= 10 THEN Unit_price * 0.9
        ELSE Unit_price
    END AS Discounted_Price
FROM Walmart_Dataset;

-- Q23. How do branches rank based on total sales?
SELECT Branch, City, SUM(Total) AS Total,
       RANK() OVER (ORDER BY SUM(Total) DESC) AS Sales_Rank
FROM Walmart_Dataset
GROUP BY Branch, City;

-- Q24. What is the rolling average of ratings per city?
SELECT City, Rating, 
       AVG(Rating) OVER (PARTITION BY City ORDER BY Date ROWS BETWEEN 4 PRECEDING AND CURRENT ROW) AS Rolling_Avg_Rating
FROM Walmart_Dataset;



